version: '3.7'

services:
  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: lamp_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./website:/var/www/html
      - ./phpmyadmin:/var/www/phpmyadmin
    networks:
      - lamp_network
    depends_on:
      - php

  # PHP Service
  php:
    build:
      context: ./php
    container_name: lamp_php
    restart: unless-stopped
    volumes:
      - ./website:/var/www/html
      - ./phpmyadmin:/var/www/phpmyadmin
    networks:
      - lamp_network
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm"]
      interval: 10s
      timeout: 5s
      retries: 3

  # MySQL Service
  mysql:
    image: mysql:8.3
    container_name: lamp_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lamp_db
      MYSQL_USER: lamp_user
      MYSQL_PASSWORD: lamp_password
    volumes:
      # Using Volume instead of Local
      # - ./mysql:/var/lib/mysql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - lamp_network


  # Redis Service
  redis:
    image: redis:alpine
    container_name: lamp_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - lamp_network

volumes:
  mysql_data:

networks:
  lamp_network:
    driver: bridge
